import { Building2 } from "lucide-react";
import {
  Apperance,
  DarsQoldirish,
  DetIcon1,
  faceMood1,
  Hijab,
  MachitIcon,
  Maska,
  Maskasvg,
  offenbicon1,
  offenbicon2,
  Soqol,
  faceMood2,
  iconMood1,
  StrangerUniver,
  hududdaTopilmagan,
  Crowdedness,
  EventMeasures,
  GirlStudents,
  CrimesStudent,
  Narkalogiya,
  BattleStudent,
  StrangerRoom,
  HealthDispensaries,
  DayTimeEducation,
  NightEducation,
  ExternalyEducation,
  GoStateStudents,
  StudentReturnsLongTime,
  StudentGoLongTime,
  LivingStudentFriends,
  RentersStudent,
  DormitersLiveStudent,
  LivengHomeStudent,
  MaskIcon,
  Hijabicon,
  BeardIcon,
} from "../assets";

const universityDashboard = [
  {
    id: 1,
    title: "Talabalar hozirgi kayfiyati bo‘yicha",
    icon: DetIcon1,
    number: 6236,
    link: "/university/:id/studentsmood",
  },
  {
    id: 2,
    title: "Dars vaqtida masjidga chiqqan talabalar",
    icon: MachitIcon,
    number: 5,
    link: "/university/:id/mechet",
  },
  {
    id: 3,
    title: "Odamlar gavjumligi",
    icon: Crowdedness,
    number: 2,
    link: "",
  },
  {
    id: 4,
    title: "Janjallar va mushtlashuvlar",
    icon: BattleStudent,
    number: 2,
    link: "",
  },
  {
    id: 5,
    title: "OTM hududiga kirgan begona shaxslar",
    icon: StrangerUniver,
    number: 91,
    link: "",
  },
  {
    id: 6,
    title: "Talabalar tashqi ko‘rinishi bo‘yicha",
    icon: Apperance,
    link: "/university/:id/appearance",
    number: 54,
  },
  {
    id: 7,
    title: "Darsga 5 va undan ortiq kun kelmagan talabalar",
    icon: DarsQoldirish,
    number: 8,
    link: "/university/:id/leave",
  },
  {
    id: 8,
    title: "Kampus hududida topilmagan talabalar",
    icon: hududdaTopilmagan,
    number: 1,
    link: "",
  },
  {
    id: 9,
    title: "Yotoqxonada begona odamlarning bo‘lishi",
    icon: StrangerRoom,
    number: 0,
    link: "",
  },
  {
    id: 10,
    title: "Hodisa bo‘yicha ko‘rilgan chora-tadbirlar",
    icon: EventMeasures,
    number: 3712,
    link: "",
  },
  {
    id: 11,
    title: "O‘gil bolalar",
    icon: DetIcon1,
    number: 3712,
    link: "",
  },
  {
    id: 12,
    title: "Qiz bolalar",
    icon: GirlStudents,
    number: 3712,
    link: "",
  },

  {
    id: 13,
    title: "Kunduzgi ta’limda o‘qiyotgan talabalar",
    link: "",
    icon: DayTimeEducation,
    number: 626,
  },
  {
    id: 14,
    title: "Kechki ta’limda o‘qiyotgan talabalar",
    icon: NightEducation,
    number: 329,
    link: "",
  },
  {
    id: 15,
    title: "Sirtqi ta’limda o‘qiyotgan talabalar",
    icon: ExternalyEducation,
    number: 8587,
    link: "",
  },
  {
    id: 16,
    title: "Chet elga chiqib ketgan talabalar",
    icon: GoStateStudents,
    number: 8885,
    link: "",
  },
  {
    id: 17,
    title: "Uzoq muddatga chiqib ketgan talabalar",
    icon: StudentGoLongTime,
    number: 112,
    link: "",
  },
  {
    id: 18,
    title: "Uzoq muddatdan qaytib kelgan talabalar",
    icon: StudentReturnsLongTime,
    number: 15148,
  },
  {
    id: 19,
    title: "Ijarada turadiganlar talabalar",
    icon: RentersStudent,
    number: 16,
  },
  {
    id: 20,
    title: "Yotoqxonada turadigan talabalar",
    icon: DormitersLiveStudent,
    number: 10618,
  },
  {
    id: 21,
    title: "Tanishinikida turgan talabalar",
    icon: LivingStudentFriends,
    number: 10618,
  },
  {
    id: 20,
    title: "Uyida yoki qarindoshinikida yashovchilar",
    icon: LivengHomeStudent,
    number: 10618,
  },
];

const OffensStudents = [
  {
    icon: offenbicon1,
    title: "Profilaktik hisobda turadigan talabalar",
    number: 0,
  },
  { icon: offenbicon2, title: "Sudlangan talabalar", number: 0 },
  {
    icon: CrimesStudent,
    title: "Talabalar tomonidan sodir etilgan jinoyatlar",
    number: 2,
  },
  {
    icon: Narkalogiya,
    title: "Narkologiya dispanseri ro`yxatida turuvchi talabalar",
    number: 250,
  },
  {
    icon: HealthDispensaries,
    title: "Ruhiy asab kasalliklari dispanseri ro`yxatida turuvchi talabalar",
    number: 3,
  },
];

const tashqikurinish1 = [
  {
    title: "Hijobda kelgan talabalar",

    icon: Hijab,
    number: 0,
  },
  {
    title: "Betartib soqol qo‘ygan talabalar",

    icon: Soqol,
    number: 0,
  },

  {
    title: "Maskada kelgan talabalar",
    icon: Maska,
    number: 10,
  },
];

const tashqikurinish2 = [
  {
    img: faceMood1,
    fullName: "KARIMJONOVFARRUX IXLOS O‘G‘LI",
    fakultet: "Geografiya",
    grux: "KKU-2205",
    icon: MaskIcon,
  },
  {
    img: faceMood1,
    fullName: "KARIMJONOVFARRUX IXLOS O‘G‘LI",
    fakultet: "Geografiya",
    grux: "KKU-2205",
    icon: Hijabicon,
  },
  {
    img: faceMood1,
    fullName: "KARIMJONOVFARRUX IXLOS O‘G‘LI",
    fakultet: "Geografiya",
    grux: "KKU-2205",
    icon: Hijabicon,
  },
  {
    img: faceMood1,
    fullName: "KARIMJONOVFARRUX IXLOS O‘G‘LI",
    fakultet: "Geografiya",
    grux: "KKU-2205",
    icon: MaskIcon,
  },
  {
    img: faceMood1,
    fullName: "KARIMJONOVFARRUX IXLOS O‘G‘LI",
    fakultet: "Geografiya",
    grux: "KKU-2205",
    icon: BeardIcon,
  },
  {
    img: faceMood1,
    fullName: "KARIMJONOVFARRUX IXLOS O‘G‘LI",
    fakultet: "Geografiya",
    grux: "KKU-2205",
    icon: Hijabicon,
  },
];

const machitStudent = [
  // 1-kun (2025-05-02)
  {
    img1: faceMood1,
    img2: faceMood2,
    foiz: 92.5,
    fullName: "KARIMJONOV FARRUX IXLOS O‘G‘LI",
    fakultet: "Geografiya",
    grux: "KKU-2205",
    machitTitle: "Исломобод масжиди Сағбон кўчаси 244-уй",
    date: "2025.05.02 - 05:00:00", // Bomdod
  },
  {
    img1: faceMood1,
    img2: faceMood2,
    foiz: 88.1,
    fullName: "ABDULLAEV JASUR SHAVKAT O‘G‘LI",
    fakultet: "Tarix",
    grux: "TTU-2104",
    machitTitle: "Исломобод масжиди Сағбон кўчаси 244-уй",
    date: "2025.05.02 - 13:00:00", // Peshin
  },
  {
    img1: faceMood1,
    img2: faceMood2,
    foiz: 81.6,
    fullName: "RAHMONOVA GULBAHOR AZIZ QIZI",
    fakultet: "Matematika",
    grux: "MMU-2301",
    machitTitle: "Исломобод масжиди Сағбон кўчаси 244-уй",
    date: "2025.05.02 - 16:30:00", // Asr
  },
  {
    img1: faceMood1,
    img2: faceMood2,
    foiz: 79.4,
    fullName: "SAIDOV AZIZBEK MANSUR O‘G‘LI",
    fakultet: "Fizika",
    grux: "FFU-2206",
    machitTitle: "Исломобод масжиди Сағбон кўчаси 244-уй",
    date: "2025.05.02 - 19:00:00", // Shom
  },
  {
    img1: faceMood1,
    img2: faceMood2,
    foiz: 84.2,
    fullName: "QODIROVA NOZIMA ISLOM QIZI",
    fakultet: "Kimyo",
    grux: "KKU-2207",
    machitTitle: "Исломобод масжиди Сағбон кўчаси 244-уй",
    date: "2025.05.02 - 21:00:00", // Xufton
  },

  // 2-kun (2025-05-03)
  {
    img1: faceMood1,
    img2: faceMood2,
    foiz: 91.3,
    fullName: "ISMOILOV DAVRON ERKIN O‘G‘LI",
    fakultet: "Informatika",
    grux: "IIU-2203",
    machitTitle: "Исломобод масжиди Сағбон кўчаси 244-уй",
    date: "2025.05.03 - 05:00:00", // Bomdod
  },
  {
    img1: faceMood1,
    img2: faceMood2,
    foiz: 87.5,
    fullName: "KARIMOVA SEVINCH BOBUR QIZI",
    fakultet: "Biologiya",
    grux: "BBU-2102",
    machitTitle: "Исломобод масжиди Сағбон кўчаси 244-уй",
    date: "2025.05.03 - 13:00:00", // Peshin
  },
  {
    img1: faceMood1,
    img2: faceMood2,
    foiz: 83.4,
    fullName: "XOLIQOV NODIRBEK SHUKUR O‘G‘LI",
    fakultet: "Huquq",
    grux: "HHU-2208",
    machitTitle: "Исломобод масжиди Сағбон кўчаси 244-уй",
    date: "2025.05.03 - 16:30:00", // Asr
  },
  {
    img1: faceMood1,
    img2: faceMood2,
    foiz: 80.6,
    fullName: "JURAEVA NILUFAR OYBEK QIZI",
    fakultet: "Psixologiya",
    grux: "PPU-2304",
    machitTitle: "Исломобод масжиди Сағбон кўчаси 244-уй",
    date: "2025.05.03 - 19:00:00", // Shom
  },
  {
    img1: faceMood1,
    img2: faceMood2,
    foiz: 85.9,
    fullName: "TOSHQULOV UMID SHAVKAT O‘G‘LI",
    fakultet: "Sport",
    grux: "SSU-2105",
    machitTitle: "Исломобод масжиди Сағбон кўчаси 244-уй",
    date: "2025.05.03 - 21:00:00", // Xufton
  },

  // 3-kun (2025-05-04)
  {
    img1: faceMood1,
    img2: faceMood2,
    foiz: 90.7,
    fullName: "YUSUPOVA MADINA QODIR QIZI",
    fakultet: "Filologiya",
    grux: "FFU-2209",
    machitTitle: "Исломобод масжиди Сағбон кўчаси 244-уй",
    date: "2025.05.04 - 05:00:00", // Bomdod
  },
  {
    img1: faceMood1,
    img2: faceMood2,
    foiz: 82.8,
    fullName: "MIRZAYEV SHERZOD JAHONGIR O‘G‘LI",
    fakultet: "Tarjima",
    grux: "TTU-2101",
    machitTitle: "Исломобод масжиди Сағбон кўчаси 244-уй",
    date: "2025.05.04 - 13:00:00", // Peshin
  },
  {
    img1: faceMood1,
    img2: faceMood2,
    foiz: 80.2,
    fullName: "ABDURAHMONOV DILSHOD ILHOM O‘G‘LI",
    fakultet: "Iqtisod",
    grux: "IIU-2202",
    machitTitle: "Исломобод масжиди Сағбон кўчаси 244-уй",
    date: "2025.05.04 - 16:30:00", // Asr
  },
  {
    img1: faceMood1,
    img2: faceMood2,
    foiz: 86.4,
    fullName: "HAMROYEVA AZIZA RUSTAM QIZI",
    fakultet: "Arxitektura",
    grux: "AAU-2307",
    machitTitle: "Исломобод масжиди Сағбон кўчаси 244-уй",
    date: "2025.05.04 - 19:00:00", // Shom
  },
  {
    img1: faceMood1,
    img2: faceMood2,
    foiz: 84.0,
    fullName: "RUSTAMOV SHERALI BOTIR O‘G‘LI",
    fakultet: "Qurilish",
    grux: "QQU-2203",
    machitTitle: "Исломобод масжиди Сағбон кўчаси 244-уй",
    date: "2025.05.04 - 21:00:00", // Xufton
  },
];

const universities = [
  {
    id: 1,
    icon: <Building2 size={30} />,
    studentCount: 32732,
    title: "O'zbekiston Milliy universiteti",
    adress: "Toshkent shahri, Olmazor tumani",
    region: "Toshkent",
  },
  {
    id: 2,
    icon: <Building2 size={30} />,
    studentCount: 21500,
    title: "Toshkent Davlat Texnika universiteti",
    adress: "Toshkent shahri, Yunusobod tumani",
    region: "Toshkent",
  },
  {
    id: 3,
    icon: <Building2 size={30} />,
    studentCount: 15000,
    title: "Andijon Davlat universiteti",
    adress: "Andijon shahri, Asaka tumani",
    region: "Andijon",
  },
  {
    id: 4,
    icon: <Building2 size={30} />,
    studentCount: 12000,
    title: "Buxoro Davlat universiteti",
    adress: "Buxoro shahri, G‘ijduvon tumani",
    region: "Buxoro",
  },
  {
    id: 5,
    icon: <Building2 size={30} />,
    studentCount: 18000,
    title: "Farg‘ona Davlat universiteti",
    adress: "Farg‘ona shahri, Marg‘ilon yo‘li",
    region: "Farg‘ona",
  },
  {
    id: 6,
    icon: <Building2 size={30} />,
    studentCount: 14000,
    title: "Jizzax Davlat pedagogika universiteti",
    adress: "Jizzax shahri, Sharof Rashidov tumani",
    region: "Jizzax",
  },
  {
    id: 7,
    icon: <Building2 size={30} />,
    studentCount: 10000,
    title: "Xorazm Davlat universiteti",
    adress: "Urganch shahri, Al-Xorazmiy ko‘chasi",
    region: "Xorazm",
  },
  {
    id: 8,
    icon: <Building2 size={30} />,
    studentCount: 16000,
    title: "Namangan Davlat universiteti",
    adress: "Namangan shahri, Chortoq yo‘li",
    region: "Namangan",
  },
  {
    id: 9,
    icon: <Building2 size={30} />,
    studentCount: 11000,
    title: "Navoiy Davlat konchilik instituti",
    adress: "Navoiy shahri, Zarafshon ko‘chasi",
    region: "Navoiy",
  },
  {
    id: 10,
    icon: <Building2 size={30} />,
    studentCount: 17500,
    title: "Qashqadaryo Davlat universiteti",
    adress: "Qarshi shahri, Mustaqillik ko‘chasi",
    region: "Qashqadaryo",
  },
  {
    id: 11,
    icon: <Building2 size={30} />,
    studentCount: 9000,
    title: "Qoraqalpoq Davlat universiteti",
    adress: "Nukus shahri, Berdaq ko‘chasi",
    region: "Qoraqalpog‘iston",
  },
  {
    id: 12,
    icon: <Building2 size={30} />,
    studentCount: 21000,
    title: "Samarqand Davlat universiteti",
    adress: "Samarqand shahri, Registon ko‘chasi",
    region: "Samarqand",
  },
  {
    id: 13,
    icon: <Building2 size={30} />,
    studentCount: 8000,
    title: "Sirdaryo Davlat universiteti",
    adress: "Guliston shahri, Mirzo Ulug‘bek ko‘chasi",
    region: "Sirdaryo",
  },
  {
    id: 14,
    icon: <Building2 size={30} />,
    studentCount: 9500,
    title: "Surxondaryo Davlat universiteti",
    adress: "Termiz shahri, Sho‘robod yo‘li",
    region: "Surxondaryo",
  },
];

const studentsMood = [
  {
    id: 1,
    img1: faceMood1,
    img2: faceMood2,
    icon: iconMood1,
    similarity: "82.45%",
    fullName: "Aliyev Jasur Bekzod o‘g‘li",
    fakultet: "Informatika",
    jins: "Erkak",
    date: "2025-01-12 14:23:00",
    gruh: "INF-21",
    age: 21,
  },
  {
    id: 2,
    img1: "/images/student2.jpg",
    img2: "/images/student2-mood.jpg",
    icon: "/icons/faculty2.png",
    similarity: "76.12%",
    fullName: "Karimova Dilnoza Anvar qizi",
    fakultet: "Matematika",
    jins: "Ayol",
    date: "2025-01-13 09:45:00",
    gruh: "MAT-22",
    age: 20,
  },
  {
    id: 3,
    img1: "/images/student3.jpg",
    img2: "/images/student3-mood.jpg",
    icon: "/icons/faculty3.png",
    similarity: "90.11%",
    fullName: "Saidov Ulug‘bek Jamshid o‘g‘li",
    fakultet: "Fizika",
    jins: "Erkak",
    date: "2025-01-14 11:10:00",
    gruh: "FIZ-20",
    age: 22,
  },
  {
    id: 4,
    img1: "/images/student4.jpg",
    img2: "/images/student4-mood.jpg",
    icon: "/icons/faculty4.png",
    similarity: "68.22%",
    fullName: "Toshpulatova Aziza Rustam qizi",
    fakultet: "Kimyo",
    jins: "Ayol",
    date: "2025-01-15 13:32:00",
    gruh: "KIM-21",
    age: 21,
  },
  {
    id: 5,
    img1: "/images/student5.jpg",
    img2: "/images/student5-mood.jpg",
    icon: "/icons/faculty5.png",
    similarity: "71.08%",
    fullName: "Ismoilov Sanjar Odil o‘g‘li",
    fakultet: "Biologiya",
    jins: "Erkak",
    date: "2025-01-16 10:11:00",
    gruh: "BIO-19",
    age: 23,
  },
  {
    id: 6,
    img1: "/images/student6.jpg",
    img2: "/images/student6-mood.jpg",
    icon: "/icons/faculty1.png",
    similarity: "84.50%",
    fullName: "Raxmonova Shahlo Botir qizi",
    fakultet: "Tarix",
    jins: "Ayol",
    date: "2025-01-17 08:54:00",
    gruh: "TAR-20",
    age: 22,
  },
  {
    id: 7,
    img1: "/images/student7.jpg",
    img2: "/images/student7-mood.jpg",
    icon: "/icons/faculty2.png",
    similarity: "65.90%",
    fullName: "Yoqubov Azizbek Rustam o‘g‘li",
    fakultet: "Huquq",
    jins: "Erkak",
    date: "2025-01-18 15:45:00",
    gruh: "HUQ-21",
    age: 21,
  },
  {
    id: 8,
    img1: "/images/student8.jpg",
    img2: "/images/student8-mood.jpg",
    icon: "/icons/faculty3.png",
    similarity: "79.34%",
    fullName: "Hamidova Madina Bahodir qizi",
    fakultet: "Filologiya",
    jins: "Ayol",
    date: "2025-01-19 17:05:00",
    gruh: "FIL-22",
    age: 20,
  },
  {
    id: 9,
    img1: "/images/student9.jpg",
    img2: "/images/student9-mood.jpg",
    icon: "/icons/faculty4.png",
    similarity: "88.10%",
    fullName: "Rustamov Nodirbek Murod o‘g‘li",
    fakultet: "Arxitektura",
    jins: "Erkak",
    date: "2025-01-20 12:41:00",
    gruh: "ARX-19",
    age: 23,
  },
  {
    id: 10,
    img1: "/images/student10.jpg",
    img2: "/images/student10-mood.jpg",
    icon: "/icons/faculty5.png",
    similarity: "74.56%",
    fullName: "To‘xtayeva Zilola Akmal qizi",
    fakultet: "Psixologiya",
    jins: "Ayol",
    date: "2025-01-21 09:30:00",
    gruh: "PSI-21",
    age: 21,
  },
  {
    id: 11,
    img1: "/images/student11.jpg",
    img2: "/images/student11-mood.jpg",
    icon: "/icons/faculty1.png",
    similarity: "92.00%",
    fullName: "Qodirov Islombek Sherzod o‘g‘li",
    fakultet: "Jurnalistika",
    jins: "Erkak",
    date: "2025-01-22 18:20:00",
    gruh: "JUR-20",
    age: 22,
  },
  {
    id: 12,
    img1: "/images/student12.jpg",
    img2: "/images/student12-mood.jpg",
    icon: "/icons/faculty2.png",
    similarity: "81.77%",
    fullName: "Xolmatova Maftuna Orif qizi",
    fakultet: "Xorijiy tillar",
    jins: "Ayol",
    date: "2025-01-23 16:05:00",
    gruh: "XOR-22",
    age: 20,
  },
  {
    id: 13,
    img1: "/images/student13.jpg",
    img2: "/images/student13-mood.jpg",
    icon: "/icons/faculty3.png",
    similarity: "67.20%",
    fullName: "Abdurahmonov Diyor Shavkat o‘g‘li",
    fakultet: "Iqtisodiyot",
    jins: "Erkak",
    date: "2025-01-24 11:55:00",
    gruh: "IQT-21",
    age: 21,
  },
  {
    id: 14,
    img1: "/images/student14.jpg",
    img2: "/images/student14-mood.jpg",
    icon: "/icons/faculty4.png",
    similarity: "73.33%",
    fullName: "Ortikova Sevara Anvar qizi",
    fakultet: "Geografiya",
    jins: "Ayol",
    date: "2025-01-25 10:40:00",
    gruh: "GEO-20",
    age: 22,
  },
  {
    id: 15,
    img1: "/images/student15.jpg",
    img2: "/images/student15-mood.jpg",
    icon: "/icons/faculty5.png",
    similarity: "86.15%",
    fullName: "Sharipov Doston Rauf o‘g‘li",
    fakultet: "Sport",
    jins: "Erkak",
    date: "2025-01-26 14:29:00",
    gruh: "SPT-19",
    age: 23,
  },
  {
    id: 16,
    img1: "/images/student16.jpg",
    img2: "/images/student16-mood.jpg",
    icon: "/icons/faculty1.png",
    similarity: "80.44%",
    fullName: "Yuldasheva Malika Farrux qizi",
    fakultet: "San’atshunoslik",
    jins: "Ayol",
    date: "2025-01-27 13:18:00",
    gruh: "SAN-21",
    age: 21,
  },
  {
    id: 1,
    img1: faceMood1,
    img2: faceMood2,
    icon: iconMood1,
    similarity: "82.45%",
    fullName: "Aliyev Jasur Bekzod o‘g‘li",
    fakultet: "Informatika",
    jins: "Erkak",
    date: "2025-01-12 14:23:00",
    gruh: "INF-21",
    age: 21,
  },
  {
    id: 2,
    img1: "/images/student2.jpg",
    img2: "/images/student2-mood.jpg",
    icon: "/icons/faculty2.png",
    similarity: "76.12%",
    fullName: "Karimova Dilnoza Anvar qizi",
    fakultet: "Matematika",
    jins: "Ayol",
    date: "2025-01-13 09:45:00",
    gruh: "MAT-22",
    age: 20,
  },
  {
    id: 3,
    img1: "/images/student3.jpg",
    img2: "/images/student3-mood.jpg",
    icon: "/icons/faculty3.png",
    similarity: "90.11%",
    fullName: "Saidov Ulug‘bek Jamshid o‘g‘li",
    fakultet: "Fizika",
    jins: "Erkak",
    date: "2025-01-14 11:10:00",
    gruh: "FIZ-20",
    age: 22,
  },
  {
    id: 4,
    img1: "/images/student4.jpg",
    img2: "/images/student4-mood.jpg",
    icon: "/icons/faculty4.png",
    similarity: "68.22%",
    fullName: "Toshpulatova Aziza Rustam qizi",
    fakultet: "Kimyo",
    jins: "Ayol",
    date: "2025-01-15 13:32:00",
    gruh: "KIM-21",
    age: 21,
  },
  {
    id: 5,
    img1: "/images/student5.jpg",
    img2: "/images/student5-mood.jpg",
    icon: "/icons/faculty5.png",
    similarity: "71.08%",
    fullName: "Ismoilov Sanjar Odil o‘g‘li",
    fakultet: "Biologiya",
    jins: "Erkak",
    date: "2025-01-16 10:11:00",
    gruh: "BIO-19",
    age: 23,
  },
  {
    id: 6,
    img1: "/images/student6.jpg",
    img2: "/images/student6-mood.jpg",
    icon: "/icons/faculty1.png",
    similarity: "84.50%",
    fullName: "Raxmonova Shahlo Botir qizi",
    fakultet: "Tarix",
    jins: "Ayol",
    date: "2025-01-17 08:54:00",
    gruh: "TAR-20",
    age: 22,
  },
  {
    id: 7,
    img1: "/images/student7.jpg",
    img2: "/images/student7-mood.jpg",
    icon: "/icons/faculty2.png",
    similarity: "65.90%",
    fullName: "Yoqubov Azizbek Rustam o‘g‘li",
    fakultet: "Huquq",
    jins: "Erkak",
    date: "2025-01-18 15:45:00",
    gruh: "HUQ-21",
    age: 21,
  },
  {
    id: 8,
    img1: "/images/student8.jpg",
    img2: "/images/student8-mood.jpg",
    icon: "/icons/faculty3.png",
    similarity: "79.34%",
    fullName: "Hamidova Madina Bahodir qizi",
    fakultet: "Filologiya",
    jins: "Ayol",
    date: "2025-01-19 17:05:00",
    gruh: "FIL-22",
    age: 20,
  },
  {
    id: 9,
    img1: "/images/student9.jpg",
    img2: "/images/student9-mood.jpg",
    icon: "/icons/faculty4.png",
    similarity: "88.10%",
    fullName: "Rustamov Nodirbek Murod o‘g‘li",
    fakultet: "Arxitektura",
    jins: "Erkak",
    date: "2025-01-20 12:41:00",
    gruh: "ARX-19",
    age: 23,
  },
  {
    id: 10,
    img1: "/images/student10.jpg",
    img2: "/images/student10-mood.jpg",
    icon: "/icons/faculty5.png",
    similarity: "74.56%",
    fullName: "To‘xtayeva Zilola Akmal qizi",
    fakultet: "Psixologiya",
    jins: "Ayol",
    date: "2025-01-21 09:30:00",
    gruh: "PSI-21",
    age: 21,
  },
  {
    id: 11,
    img1: "/images/student11.jpg",
    img2: "/images/student11-mood.jpg",
    icon: "/icons/faculty1.png",
    similarity: "92.00%",
    fullName: "Qodirov Islombek Sherzod o‘g‘li",
    fakultet: "Jurnalistika",
    jins: "Erkak",
    date: "2025-01-22 18:20:00",
    gruh: "JUR-20",
    age: 22,
  },
  {
    id: 12,
    img1: "/images/student12.jpg",
    img2: "/images/student12-mood.jpg",
    icon: "/icons/faculty2.png",
    similarity: "81.77%",
    fullName: "Xolmatova Maftuna Orif qizi",
    fakultet: "Xorijiy tillar",
    jins: "Ayol",
    date: "2025-01-23 16:05:00",
    gruh: "XOR-22",
    age: 20,
  },
  {
    id: 13,
    img1: "/images/student13.jpg",
    img2: "/images/student13-mood.jpg",
    icon: "/icons/faculty3.png",
    similarity: "67.20%",
    fullName: "Abdurahmonov Diyor Shavkat o‘g‘li",
    fakultet: "Iqtisodiyot",
    jins: "Erkak",
    date: "2025-01-24 11:55:00",
    gruh: "IQT-21",
    age: 21,
  },
  {
    id: 14,
    img1: "/images/student14.jpg",
    img2: "/images/student14-mood.jpg",
    icon: "/icons/faculty4.png",
    similarity: "73.33%",
    fullName: "Ortikova Sevara Anvar qizi",
    fakultet: "Geografiya",
    jins: "Ayol",
    date: "2025-01-25 10:40:00",
    gruh: "GEO-20",
    age: 22,
  },
  {
    id: 15,
    img1: "/images/student15.jpg",
    img2: "/images/student15-mood.jpg",
    icon: "/icons/faculty5.png",
    similarity: "86.15%",
    fullName: "Sharipov Doston Rauf o‘g‘li",
    fakultet: "Sport",
    jins: "Erkak",
    date: "2025-01-26 14:29:00",
    gruh: "SPT-19",
    age: 23,
  },
  {
    id: 16,
    img1: "/images/student16.jpg",
    img2: "/images/student16-mood.jpg",
    icon: "/icons/faculty1.png",
    similarity: "80.44%",
    fullName: "Yuldasheva Malika Farrux qizi",
    fakultet: "San’atshunoslik",
    jins: "Ayol",
    date: "2025-01-27 13:18:00",
    gruh: "SAN-21",
    age: 21,
  },
];
export {
  universityDashboard,
  machitStudent,
  OffensStudents,
  tashqikurinish1,
  tashqikurinish2,
  universities,
  studentsMood,
};
