export const StudentsData = [
  {
    id: 1,
    img: "https://i.pravatar.cc/50?img=1",
    fullName: "FAYZULLAYEVA GULBAHOR .Z",
    talabaKartochka: "Xodim kartochkasi",
    darsJadvali: "Dars jadvali",
    profilaktika: "Profilaktika",
    jshshir: "12345678901234",
    universitet: "Buxoro innovatsion ta'lim va tibbiyot",
    fakultet: "Iqtisodiyot (Tarmoqlar va sohalar bo'yicha)",
    grux: "-",
    yashashManzil: "Toshkent, Chilonzor-5",
    hodisalar: "0",
    ogohlantirishlar: "0 ",
    qoidabuzarliklar: "0",
  },
  {
    id: 2,
    img: "https://i.pravatar.cc/50?img=1",
    fullName: "SHAMSIYEV BEHZOD .S",
    talabaKartochka: "Xodim kartochkasi",
    darsJadvali: "Dars jadvali",
    profilaktika: "Profilaktika",
    jshshir: "52409035360058",
    universitet: "Buxoro innovatsion ta'lim va tibbiyot",
    fakultet: "Psixologiya (Faoliyat turlari bo'yicha)",
    grux: "-",
    yashashManzil: "Toshkent, Olmazor-5",
    hodisalar: "0",
    ogohlantirishlar: "0 ",
    qoidabuzarliklar: "0",
  },

  {
    id: 3,
    img: "https://i.pravatar.cc/50?img=1",
    fullName: "SHIRINOVA GULMIRA .N",
    talabaKartochka: "Xodim kartochkasi",
    darsJadvali: "Dars jadvali",
    profilaktika: "Profilaktika",
    jshshir: "42707965310109",
    universitet: "Buxoro innovatsion ta'lim va tibbiyot",
    fakultet: "Psixologiya (Faoliyat turlari bo'yicha)",
    grux: "-",
    yashashManzil: "Toshkent, Yashnabod-1",
    hodisalar: "0",
    ogohlantirishlar: "0 ",
    qoidabuzarliklar: "0",
  },

  {
    id: 4,
    img: "https://i.pravatar.cc/50?img=1",
    fullName: "AHMED ELHUSSEIN .V",
    talabaKartochka: "Xodim kartochkasi",
    darsJadvali: "Dars jadvali",
    profilaktika: "Profilaktika",
    jshshir: "50404058330011",
    universitet: "Buxoro innovatsion ta'lim va tibbiyot",
    fakultet: "Davolash ishi va Stomatologiya",
    grux: "-",
    yashashManzil: "Toshkent, Sergeli-12",
    hodisalar: "0",
    ogohlantirishlar: "0 ",
    qoidabuzarliklar: "0",
  },

  {
    id: 5,
    img: "https://i.pravatar.cc/50?img=1",
    fullName: "BOLTAYEV FIRUZBEK .B",
    talabaKartochka: "Xodim kartochkasi",
    darsJadvali: "Dars jadvali",
    profilaktika: "Profilaktika",
    jshshir: "52502025280054",
    universitet: "Buxoro innovatsion ta'lim va tibbiyot",
    fakultet: "Iqtisodiyot (Tarmoqlar va sohalar bo'yicha)",
    grux: "-",
    yashashManzil: "Toshkent, Chilonzor-3",
    hodisalar: "0",
    ogohlantirishlar: "0 ",
    qoidabuzarliklar: "0",
  },

  {
    id: 6,
    img: "https://i.pravatar.cc/50?img=1",
    fullName: "SHUKURLAYEV JASURBEK .J",
    talabaKartochka: "Xodim kartochkasi",
    darsJadvali: "Dars jadvali",
    profilaktika: "Profilaktika",
    jshshir: "31911921000016",
    universitet: "Buxoro innovatsion ta'lim va tibbiyot",
    fakultet: "Iqtisodiyot (Tarmoqlar va sohalar bo'yicha)",
    grux: "-",
    yashashManzil: "Toshkent, Chilonzor-5",
    hodisalar: "0",
    ogohlantirishlar: "0 ",
    qoidabuzarliklar: "0",
  },
];
